swagger: "2.0"
info:
  description: Swagger doc for /api/sys/firmware_info_pim
  title: Swagger doc for /api/sys/firmware_info_pim
  version: 1.0.0
paths:
  /api/sys/firmware_info_pim:
    get:
      produces: [application/json]
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Resources:
                type: array
                items:
                  type: string
              Actions:
                type: array
                items:
                  type: string
              Information:
                type: object
                additionalProperties: false
                properties:
                  "1": &pim_block
                    type: object
                    properties:
                      "status":
                        type: string
                        pattern: "^(present|missing)$"
                      "version":
                        type: string
                        pattern: "^[0-9]+[.][0-9]+$"
                      "type":
                        type: string
                        pattern: "[0-9a-zA-Z]"
                  "2":
                    <<: *pim_block
                  "3":
                    <<: *pim_block
                  "4":
                    <<: *pim_block
                  "5":
                    <<: *pim_block
                  "6":
                    <<: *pim_block
                  "7":
                    <<: *pim_block
                  "8":
                    <<: *pim_block
