swagger: "2.0"
info: 
  description: Swagger doc for /api/server1/sensors  
  title: Swagger doc for /api/server1/sensors  
  version: 1.0.0
paths: 
  /api/server1/sensors: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: false
                properties: 
                  MB_INLET_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_OUTLET_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  FIO_FRONT_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_SOC_CPU_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_DIMMA0_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_DIMMA1_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_DIMMA2_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_DIMMA4_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_DIMMA6_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_DIMMA7_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_DIMMA8_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_DIMMA10_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_SSD0_M2A_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_HSC_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_SOC_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_PVDDIO_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_PVDD11_TEMP_C: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_P12V_STBY_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_PVDD18_S5_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_P3V3_STBY_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_PVDD11_S3_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_P3V_BAT_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_PVDD33_S5_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_P5V_STBY_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_P12V_MEM_1_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_P12V_MEM_0_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_P1V2_STBY_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_P3V3_M2_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_ADC_P1V8_STBY_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_HSC_INPUT_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_SOC_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_PVDDIO_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_PVDD11_VOLT_V: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  HSC_OUTPUT_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_SOC_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_PVDDIO_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_PVDD11_CURR_A: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_HSC_INPUT_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU0_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_SOC_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_CPU1_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_PVDDIO_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_PVDD11_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_SOC_PACKAGE_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_DIMMA0_PMIC_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_DIMMA1_PMIC_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_DIMMA2_PMIC_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_DIMMA4_PMIC_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_DIMMA6_PMIC_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_DIMMA7_PMIC_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_DIMMA8_PMIC_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
                  MB_VR_DIMMA10_PMIC_PWR_W: 
                    type: object
                    additionalProperties: false
                    properties: 
                      value: 
                        type: string
              Actions: 
                type: array
                items: 
                  type: string
              Resources: 
                type: array
                items: 
                  type: string
            