[package]
name = "fbqemu"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/facebook/openbmc"
license = "GPL-2.0-only"
description = "fb wrapper around QEMU"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.61"
clap = {version = "3.2.16", features = ["derive", "env"]}
fdt = "0.1.4"
tempfile = "3.3.0"
